# Generated by Django 5.0.2 on 2024-03-08 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomLocal', models.CharField(max_length=32)),
                ('typelocal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('marque', models.CharField(max_length=100)),
                ('etat', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=100)),
                ('categorie', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=50)),
                ('puissance', models.FloatField()),
                ('maxConsommation', models.FloatField()),
                ('minConsommation', models.FloatField()),
                ('zoneE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.zone')),
            ],
        ),
    ]
