# Generated by Django 5.0.2 on 2024-03-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_zone_equipement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numEtage', models.IntegerField()),
                ('surface', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='zone',
            name='etageZ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quickstart.etage'),
            preserve_default=False,
        ),
    ]
