# Generated by Django 5.0.2 on 2024-03-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_etage_zone_etagez'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etage',
            name='numEtage',
        ),
    ]
