# Generated by Django 5.0.2 on 2024-03-24 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_exceldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomBatiment', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempsDebut', models.DateTimeField()),
                ('tempsFin', models.DateTimeField(blank=True, null=True)),
                ('consommation', models.FloatField(blank=True, null=True)),
                ('Equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.equipement')),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AddField(
            model_name='zone',
            name='maxH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='maxT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='minH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='minT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etage',
            name='batimentId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quickstart.batiment'),
            preserve_default=False,
        ),
    ]
