# Generated by Django 5.0.2 on 2024-03-24 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_batiment_periodeactivite_delete_movie_zone_maxh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=32)),
                ('equipementId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.equipement')),
            ],
        ),
    ]
