# Generated by Django 5.0.2 on 2024-03-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_alerte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batiment',
            name='nomBatiment',
            field=models.CharField(max_length=500),
        ),
    ]
