# Generated by Django 5.0.2 on 2024-03-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_alter_batiment_nombatiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='etage',
            name='nomEtage',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
