# Generated by Django 5.0.2 on 2024-03-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_alter_etage_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='surface',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='typeLocal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
