# Generated by Django 5.0.2 on 2024-03-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_alter_zone_surface_alter_zone_typelocal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='nomLocal',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='zone',
            name='typeLocal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
