# Generated by Django 5.0.2 on 2024-03-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_alter_zone_nomlocal_alter_zone_typelocal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='type',
        ),
        migrations.AlterField(
            model_name='equipement',
            name='categorie',
            field=models.CharField(choices=[('critique', 'critique'), ('normal', 'normal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='maxConsommation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='minConsommation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='nom',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='puissance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
