# Generated by Django 5.0.2 on 2024-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0015_remove_equipement_marque_remove_equipement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='categorie',
            field=models.CharField(choices=[('critique', 'critique'), ('normal', 'normal')], default='normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='etat',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=100),
        ),
    ]
