# Generated by Django 5.0.2 on 2024-04-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0016_alter_equipement_categorie_alter_equipement_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='typeBatiment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
