# Generated by Django 5.0.2 on 2024-04-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0017_batiment_typebatiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etage',
            name='nomEtage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
