# Generated by Django 5.0.2 on 2024-04-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0018_alter_etage_nometage'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
