# Generated by Django 5.0.2 on 2024-04-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0019_alerte_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerte',
            name='type',
        ),
    ]
