# Generated by Django 5.0.2 on 2024-04-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0021_useraccount'),
    ]

    operations = [
    ]
