# Generated by Django 5.0.2 on 2024-04-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0022_auto_20240421_2031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
