# Generated by Django 5.0.4 on 2024-04-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0024_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
