# Generated by Django 5.0.4 on 2024-04-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0026_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
