# Generated by Django 5.0.4 on 2024-04-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0028_customuser_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
