# Generated by Django 5.0.4 on 2024-04-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0032_profileuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='user',
            new_name='userId',
        ),
    ]
