# Generated by Django 5.0.4 on 2024-04-30 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0033_rename_user_profileuser_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='localId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.zone'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='equipementId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.equipement'),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
