# Generated by Django 5.0.4 on 2024-05-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0034_alerte_localid_alerte_type_alter_alerte_equipementid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='dateAlerte',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
