# Generated by Django 5.0.4 on 2024-05-05 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0036_alerte_userid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='notifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerte',
            name='valeur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='vu',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causes', models.CharField(blank=True, max_length=2000, null=True)),
                ('solutions', models.CharField(blank=True, max_length=2000, null=True)),
                ('risques', models.CharField(blank=True, max_length=2000, null=True)),
                ('equipementsDemandes', models.CharField(blank=True, max_length=2000, null=True)),
                ('equipementsNecessites', models.CharField(blank=True, max_length=2000, null=True)),
                ('alerte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.alerte')),
                ('redacteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RapportEquipementEndommage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.equipement')),
                ('rapport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.rapport')),
            ],
        ),
    ]
