# Generated by Django 5.0.4 on 2024-05-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0037_alerte_notifie_alerte_valeur_alerte_vu_rapport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='dateFinAlerte',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
