# Generated by Django 5.0.4 on 2024-05-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0038_alerte_datefinalerte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerte',
            name='dateFinAlerte',
        ),
    ]
