# Generated by Django 5.0.4 on 2024-05-07 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0039_remove_alerte_datefinalerte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.equipement'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textN', models.CharField(blank=True, max_length=500, null=True)),
                ('dateNotification', models.DateTimeField(blank=True, null=True)),
                ('notifieN', models.BooleanField(default=False)),
                ('vuN', models.BooleanField(default=False)),
                ('rapportN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.rapport')),
                ('userIDN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RapportEquipementEndommage',
        ),
    ]
