# Generated by Django 5.0.4 on 2024-05-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0040_rapport_equipement_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='dateRapport',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='notifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rapport',
            name='vu',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
