# Generated by Django 5.0.4 on 2024-05-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0041_rapport_daterapport_rapport_notifie_rapport_vu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
