# Generated by Django 5.0.4 on 2024-05-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0042_equipement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='maxConsommation',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='minConsommation',
        ),
    ]
