# Generated by Django 5.0.4 on 2024-05-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0043_remove_equipement_maxconsommation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='categorie',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='type',
            field=models.CharField(choices=[('critique', 'critique'), ('normal', 'normal')], default='normal', max_length=100),
        ),
    ]
